name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-cpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r requirements-dev.txt
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/ --cov=src/ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml 

    - name: Cache pip packages
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache HF models
      uses: actions/cache@v2
      with:
        path: ~/.cache/huggingface
        key: ${{ runner.os }}-hf-${{ hashFiles('src/config.py') }}
        restore-keys: |
          ${{ runner.os }}-hf-

  test-gpu:
    runs-on: ubuntu-latest
    continue-on-error: true  # Make GPU tests optional
    container:
      image: nvidia/cuda:11.8.0-base-ubuntu22.04
      options: --gpus all
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y python3-pip ffmpeg
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-timeout
        pip install -r requirements.txt
        pip install -e .
    
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest tests/ --cov=src/ --cov-report=xml 